"use client";

import { useEffect, useMemo, useState } from "react";

import {
  fetchInternalAdminNotifications,
  type AdminNotificationListItem,
} from "@/lib/admin-notifications-api";
import { AdminNotificationsList } from "./AdminNotificationsList";

function getErrorMessage(error: unknown): string {
  if (error instanceof Error && error.message.trim().length > 0) {
    return error.message;
  }

  return "Unable to load notifications right now.";
}

export function AdminNotificationsPanel() {
  const [notifications, setNotifications] = useState<AdminNotificationListItem[]>([]);
  const [isInitialLoading, setIsInitialLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);

  async function loadNotifications(mode: "initial" | "refresh" = "refresh"): Promise<void> {
    if (mode === "initial") {
      setIsInitialLoading(true);
    } else {
      setIsRefreshing(true);
    }

    try {
      const result = await fetchInternalAdminNotifications();
      setNotifications(result);
      setLoadError(null);
    } catch (error) {
      setLoadError(getErrorMessage(error));
    } finally {
      if (mode === "initial") {
        setIsInitialLoading(false);
      } else {
        setIsRefreshing(false);
      }
    }
  }

  useEffect(() => {
    void loadNotifications("initial");
  }, []);

  const countLabel = useMemo(() => `${notifications.length} internal events`, [notifications.length]);

  return (
    <div className="admin-notifications-panel">
      <section className="admin-bookings-toolbar">
        <div>
          <h2 className="heading-sm serif" style={{ marginBottom: "0.5rem" }}>
            Notification Operations Log
          </h2>
          <p className="text-secondary" style={{ fontSize: "0.92rem" }}>
            Track notification intents and delivery outcomes generated by booking and staff workflows.
          </p>
        </div>

        <div className="admin-notifications-toolbar-controls">
          <span className="admin-count-pill">{countLabel}</span>
          <button
            type="button"
            className="btn btn-outline-primary"
            disabled={isInitialLoading || isRefreshing}
            onClick={() => void loadNotifications("refresh")}
          >
            {isRefreshing ? "Refreshing..." : "Refresh Notifications"}
          </button>
        </div>
      </section>

      <AdminNotificationsList
        notifications={notifications}
        isLoading={isInitialLoading}
        loadError={loadError}
      />
    </div>
  );
}
